# Runs Home app
version: '3.1'

services:
  home:
    image: geopython/demo.pygeoapi.io:latest
    # OLD pygeoapi/home:latest

    container_name: home

    labels:
      - "traefik.backend=home_app"
      - "traefik.enable=true"
      - "traefik.frontend.priority=5"
      - "traefik.frontend.rule=Host:demo.pygeoapi.io; PathPrefixStrip:/"
      - "traefik.docker.network=pygeoapi-network"

networks:
  default:
    external:
      name: pygeoapi-network
