server:
    bind:
        host: 0.0.0.0
        port: 80
    url: https://demo.pygeoapi.io/covid-19
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    cors: true
    pretty_print: true
    limit: 10
    # templates: /path/to/templates
    map:
        url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
        attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: pygeoapi COVID-19 instance
        description: pygeoapi instance in support of COVID-19 data from JHU
        keywords:
            - covid-19
            - coronavirus
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: null
        url: https://pygeoapi.io
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: pygeoapi
        url: https://pygeoapi.io
    contact:
        name: Tom Kralidis
        position: Senior Systems Scientist
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: pygeoapi@lists.osgeo.org
        url: https://pygeoapi.io/community/
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

datasets:
    cases:
        title: "Cases - Coronavirus 2019 nCoV Cases"
        description: "Current situation for the noval coronavirus starting from Wuhan, China"
        keywords: [Daily, Cases, Country, Province, State]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: Coronavirus COVID-19 Global Cases by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University (JHU)
              href: https://coronavirus.jhu.edu/map.html
              hreflang: en-US
            - type: text/html
              rel: canonical
              title: "ArcGIS instance with the current situation for the novel coronavirus starting from Wuhan, China"
              href: https://www.arcgis.com/home/item.html?id=c0b356e20b30490c8b8b4c7bb9554e7c&view=list#overview
              hreflang: en-US
            - type: text/html
              rel: download
              title: "Novel Coronavirus (COVID-19) Cases, provided by JHU CSSE"
              href: https://github.com/CSSEGISandData/COVID-19
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2020-01-01
                end: null # or empty

        provider:
            name: OGR
            data:
                source_type: ESRIJSON
                source: https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases/FeatureServer/1/query?where=objectid+%3D+objectid&outfields=*&orderByFields=OBJECTID+ASC&f=json
                source_srs: EPSG:4326
                target_srs: EPSG:4326
                source_capabilities:
                    paging: True
                open_options:
                    FEATURE_SERVER_PAGING: YES
                gdal_ogr_options:
                    EMPTY_AS_NULL: NO
                    GDAL_CACHEMAX: 64
                    # GDAL_HTTP_PROXY: (optional proxy)
                    # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                    CPL_DEBUG: NO
            id_field: OBJECTID
            layer: ESRIJSON

    cases_country:
        title: "Cases by country - Coronavirus 2019 nCoV Cases"
        description: "Current situation for the noval coronavirus starting from Wuhan, China"
        keywords: [Daily, Cases, Country, Province, State]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: Coronavirus COVID-19 Global Cases by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University (JHU)
              href: https://coronavirus.jhu.edu/map.html
              hreflang: en-US
            - type: text/html
              rel: canonical
              title: "ArcGIS instance with the current situation for the novel coronavirus starting from Wuhan, China"
              href: https://www.arcgis.com/home/item.html?id=c0b356e20b30490c8b8b4c7bb9554e7c&view=list#overview
              hreflang: en-US
            - type: text/html
              rel: download
              title: "Novel Coronavirus (COVID-19) Cases, provided by JHU CSSE"
              href: https://github.com/CSSEGISandData/COVID-19
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2020-01-01
                end: null # or empty

        provider:
            name: OGR
            data:
                source_type: ESRIJSON
                source: https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/ncov_cases/FeatureServer/2/query?where=objectid+%3D+objectid&outfields=*&orderByFields=OBJECTID+ASC&f=json
                source_srs: EPSG:4326
                target_srs: EPSG:4326
                source_capabilities:
                    paging: True
                open_options:
                    FEATURE_SERVER_PAGING: YES
                gdal_ogr_options:
                    EMPTY_AS_NULL: NO
                    GDAL_CACHEMAX: 64
                    # GDAL_HTTP_PROXY: (optional proxy)
                    # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                    CPL_DEBUG: NO
            id_field: OBJECTID
            layer: ESRIJSON

    cases_netherlands_per_municipality:
        title: "Cases in The Netherlands - Per Municipality - Points"
        description: "Current situation within The Netherlands, number of cases per Municipality, provided by ESRI NL, source data from RIVM. Point Layer."
        keywords: [Daily, Cases, Municipality]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: "ArcGIS instance with the current situation for number of COVID-19 cases per municipality in The Netherlands - Points"
              href: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/CoronavirusPunten/FeatureServer/0?f=html
              hreflang: en-US
            - type: text/html
              rel: download
              title: "ArcGIS instance with the current situation for number of COVID-19 cases per municipality in The Netherlands - Points"
              href: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/CoronavirusPunten/FeatureServer
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2020-01-01
                end: null # or empty

        provider:
            name: OGR
            data:
                source_type: ESRIJSON
                source: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/CoronavirusPunten/FeatureServer/0/query?where=objectid+%3D+objectid&outfields=*&orderByFields=OBJECTID+ASC&f=json
                source_srs: EPSG:28992
                target_srs: EPSG:4326
                source_capabilities:
                    paging: True
                open_options:
                    FEATURE_SERVER_PAGING: YES
                gdal_ogr_options:
                    EMPTY_AS_NULL: NO
                    GDAL_CACHEMAX: 64
                    # GDAL_HTTP_PROXY: (optional proxy)
                    # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                    CPL_DEBUG: NO
            id_field: OBJECTID
            layer: ESRIJSON

    cases_netherlands_per_municipality_polygons:
        title: "Cases in The Netherlands - Per Municipality - Polygons"
        description: "Current situation within The Netherlands, number of cases per Municipality, provided by ESRI NL, source data from RIVM. Polygon Layer."
        keywords: [Daily, Cases, Municipality]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: "ArcGIS instance with the current situation for number of COVID-19 cases per municipality in The Netherlands - Polygons"
              href: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/CoronaOpenbaar/FeatureServer/0?f=html
              hreflang: en-US
            - type: text/html
              rel: download
              title: "ArcGIS instance with the current situation for number of COVID-19 cases per municipality in The Netherlands - Polygons"
              href: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/CoronaOpenbaar/FeatureServer
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2020-01-01
                end: null # or empty

        provider:
            name: OGR
            data:
                source_type: ESRIJSON
                source: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/CoronaOpenbaar/FeatureServer/0/query?where=objectid+%3D+objectid&outfields=*&orderByFields=OBJECTID+ASC&f=json
                source_srs: EPSG:28992
                target_srs: EPSG:4326
                source_capabilities:
                    paging: True
                open_options:
                    FEATURE_SERVER_PAGING: YES
                gdal_ogr_options:
                    EMPTY_AS_NULL: NO
                    GDAL_CACHEMAX: 64
                    # GDAL_HTTP_PROXY: (optional proxy)
                    # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                    CPL_DEBUG: NO
            id_field: OBJECTID
            layer: ESRIJSON

    cases_netherlands_hospitalized_per_municipality:
        title: "The Netherlands - Persons Hospitalized Per Municipality - Points"
        description: "Current situation within The Netherlands, number of patients hospitalized per Municipality, provided by ESRI NL, source data from RIVM. Point Layer."
        keywords: [Daily, Cases, Municipality, Hospital]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: "ArcGIS instance with the current situation for number of COVID-19 cases hospitalized per municipality in The Netherlands - Points"
              href: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/Coronavirus_ziekenhuisopnamen_punt/FeatureServer/0?f=html
              hreflang: en-US
            - type: text/html
              rel: download
              title: "ArcGIS instance with the current situation for number of COVID-19 cases hospitalized per municipality in The Netherlands - Points"
              href: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/Coronavirus_ziekenhuisopnamen_punt/FeatureServer
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2020-01-01
                end: null # or empty

        provider:
            name: OGR
            data:
                source_type: ESRIJSON
                source: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/Coronavirus_ziekenhuisopnamen_punt/FeatureServer/0/query?where=objectid+%3D+objectid&outfields=*&orderByFields=OBJECTID+ASC&f=json
                source_srs: EPSG:28992
                target_srs: EPSG:4326
                source_capabilities:
                    paging: True
                open_options:
                    FEATURE_SERVER_PAGING: YES
                gdal_ogr_options:
                    EMPTY_AS_NULL: NO
                    GDAL_CACHEMAX: 64
                    # GDAL_HTTP_PROXY: (optional proxy)
                    # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                    CPL_DEBUG: NO
            id_field: OBJECTID
            layer: ESRIJSON

    cases_netherlands_hospitalized_per_municipality_polygons:
        title: "The Netherlands - Persons Hospitalized Per Municipality - Polygons"
        description: "Current situation within The Netherlands, number of patients hospitalized per Municipality, provided by ESRI NL, source data from RIVM. Polygon Layer."
        keywords: [Daily, Cases, Municipality, Hospital]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: "ArcGIS instance with the current situation for number of COVID-19 cases hospitalized per municipality in The Netherlands - Polygons"
              href: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/Coronavirus_ziekenhuisopnamen_vlak/FeatureServer/0?f=html
              hreflang: en-US
            - type: text/html
              rel: download
              title: "ArcGIS instance with the current situation for number of COVID-19 cases hospitalized per municipality in The Netherlands - Polygons"
              href: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/Coronavirus_ziekenhuisopnamen_vlak/FeatureServer
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2020-01-01
                end: null # or empty

        provider:
            name: OGR
            data:
                source_type: ESRIJSON
                source: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/Coronavirus_ziekenhuisopnamen_vlak/FeatureServer/0/query?where=objectid+%3D+objectid&outfields=*&orderByFields=OBJECTID+ASC&f=json
                source_srs: EPSG:28992
                target_srs: EPSG:4326
                source_capabilities:
                    paging: True
                open_options:
                    FEATURE_SERVER_PAGING: YES
                gdal_ogr_options:
                    EMPTY_AS_NULL: NO
                    GDAL_CACHEMAX: 64
                    # GDAL_HTTP_PROXY: (optional proxy)
                    # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                    CPL_DEBUG: NO
            id_field: OBJECTID
            layer: ESRIJSON

    cases_netherlands_hospitalized_per_municipality_time:
        title: "The Netherlands - Persons Hospitalized Per Municipality over Time - Points"
        description: "Current situation within The Netherlands, number of patients hospitalized per Municipality over Time, provided by ESRI NL, source data from RIVM. Point and Time Layer."
        keywords: [Daily, Cases, Municipality, Hospital]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: "ArcGIS instance with the current situation for number of COVID-19 cases hospitalized per municipality in The Netherlands - Point and Time Layer."
              href: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/Coronavirus_ziekenhuisopnamen_tijd_punt/FeatureServer/0?f=html
              hreflang: en-US
            - type: text/html
              rel: download
              title: "ArcGIS instance with the current situation for number of COVID-19 cases hospitalized per municipality in The Netherlands - Point and Time Layer."
              href: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/Coronavirus_ziekenhuisopnamen_tijd_punt/FeatureServer
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2020-01-01
                end: null # or empty

        provider:
            name: OGR
            data:
                source_type: ESRIJSON
                source: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/Coronavirus_ziekenhuisopnamen_tijd_punt/FeatureServer/0/query?where=objectid+%3D+objectid&outfields=*&orderByFields=OBJECTID+ASC&f=json
                source_srs: EPSG:28992
                target_srs: EPSG:4326
                source_capabilities:
                    paging: True
                open_options:
                    FEATURE_SERVER_PAGING: YES
                gdal_ogr_options:
                    EMPTY_AS_NULL: NO
                    GDAL_CACHEMAX: 64
                    # GDAL_HTTP_PROXY: (optional proxy)
                    # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                    CPL_DEBUG: NO
            id_field: OBJECTID
            layer: ESRIJSON

    cases_netherlands_hospitalized_per_municipality_time_polygons:
        title: "The Netherlands - Persons Hospitalized Per Municipality over Time - Polygons"
        description: "Current situation within The Netherlands, number of patients hospitalized per Municipality over Time, provided by ESRI NL, source data from RIVM. Polygon and Time Layer."
        keywords: [Daily, Cases, Municipality, Hospital]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: "ArcGIS instance with the current situation for number of COVID-19 cases hospitalized per municipality in The Netherlands - Polygon and Time Layer."
              href: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/Coronavirus_ziekenhuisopnamen_tijd_vlak/FeatureServer/0?f=html
              hreflang: en-US
            - type: text/html
              rel: download
              title: "ArcGIS instance with the current situation for number of COVID-19 cases hospitalized per municipality in The Netherlands - Polygon and Time Layer."
              href: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/Coronavirus_ziekenhuisopnamen_tijd_vlak/FeatureServer
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2020-01-01
                end: null # or empty

        provider:
            name: OGR
            data:
                source_type: ESRIJSON
                source: https://services.arcgis.com/nSZVuSZjHpEZZbRo/ArcGIS/rest/services/Coronavirus_ziekenhuisopnamen_tijd_vlak/FeatureServer/0/query?where=objectid+%3D+objectid&outfields=*&orderByFields=OBJECTID+ASC&f=json
                source_srs: EPSG:28992
                target_srs: EPSG:4326
                source_capabilities:
                    paging: True
                open_options:
                    FEATURE_SERVER_PAGING: YES
                gdal_ogr_options:
                    EMPTY_AS_NULL: NO
                    GDAL_CACHEMAX: 64
                    # GDAL_HTTP_PROXY: (optional proxy)
                    # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                    CPL_DEBUG: NO
            id_field: OBJECTID
            layer: ESRIJSON
