version: "3"

services:

  pygeoapi:
    
    image: geopython/pygeoapi_demo:latest

    container_name: pygeoapi

    restart: unless-stopped

    expose:
      - "80"

    ports:
      - "5000:80"

    environment:
     - SCRIPT_NAME=/pygeoapi

    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:demo.pygeoapi.io,localhost;PathPrefix:/pygeoapi"
      - "traefik.backend=pygeoapi"
      - "traefik.frontend.priority=100"
      - "traefik.docker.network=pygeoapi-network"

networks:
  default:
    external:
      name: pygeoapi-network
